name: Lint All

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  lint-all:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Lint PHP files
      run: |
        composer install
        composer lint